### ISSUE TITLE
swipe card web form for boffin link

### ISSUE THREAD

**Issue by mkijowski** [BoffinFactory/Hello-world#7]

**Comment by mbriningstool** [comment]
What is normal turn around for access? A week or possibly longer?

**Comment by wkjid10t** [comment]
If nobody wants to touch this. Let me know. I can put together a simple Web-App. I can host on firebase which would be secure. 
Not sure if you'd rather host internal. If so, not sure how much I can help with serving. Slightly busy.

I can still put together the front end if you want, then you can assign someone to figure out the hosting/backend at wsu

**Comment by pattonsgirl** [comment]
Swipe card processing has been fixed.  From here forward, standard turn around should be 1-2 business days.
