### ISSUE TITLE
fall fest friday

### ISSUE THREAD

**Issue by mkijowski** [BoffinFactory/Hello-world#8]
share with SWE?  department table?

**Comment by wkjid10t** [comment]
I'm ok with that

**Comment by mkijowski** [comment]
Lol good. I saw you were still a member, wasn't sure if you were paying attention;)   If you guys come down you'll have to come to a boffin night and kick some kids into shape.

We're making the kids do everything for boffin and ACM on github this year.  Should be fun to see the disaster that is our first year commits and management...

**Comment by mbriningstool** [comment]
Fall fest has come and passed. Please close this issue.
